name: One or more event triggers

on:
  schedule:
    - cron: "*/5 * * * *"
  issues:
    types: [opened]
  push:
    branches: [ "push" ]

jobs:
  testevent:
    runs-on: ubuntu-latest
    
    steps:
    - run: echo Hello from test
